/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/


// src/userscript-modules/string.ts
var string_default = "Hello from VS Code,my dear!";

// src/userscript.ts
console.log(string_default);
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsic3JjL3VzZXJzY3JpcHQtbW9kdWxlcy9zdHJpbmcudHMiLCAic3JjL3VzZXJzY3JpcHQudHMiXSwKICAic291cmNlc0NvbnRlbnQiOiBbImV4cG9ydCBkZWZhdWx0ICdIZWxsbyBmcm9tIFZTIENvZGUsbXkgZGVhciEnO1xuIiwgImltcG9ydCBzdHIgZnJvbSAnLi91c2Vyc2NyaXB0LW1vZHVsZXMvc3RyaW5nJztcblxuY29uc29sZS5sb2coc3RyKTtcbiJdLAogICJtYXBwaW5ncyI6ICI7Ozs7Ozs7QUFBQSxJQUFPLGlCQUFROzs7QUNFZixRQUFRLElBQUksY0FBRzsiLAogICJuYW1lcyI6IFtdCn0K
